Update SECURITY.md
tcdi/plrust pull request #356
Opened 2023-07-12 19:19 UTC by johnrballard

Added github advisory reporting for security related findings.

2023-07-12 19:40 UTC, workingjubilee approved these changes
Looks good.

2023-07-12 19:43 UTC, eeeebbbbrrrr requested changes

2023-07-12 19:43 UTC, eeeebbbbrrrr commented on SECURITY.md
> +Instead, please open a [security advisory][advisory] which notify the maintainers. You should receive a response within 3 working days. If for some reason you do not, please follow up via email to en
"which **notifies**"?

2023-07-12 19:48 UTC, workingjubilee commented on SECURITY.md
> +Instead, please open a [security advisory][advisory] which notify the maintainers. You should receive a response within 3 working days. If for some reason you do not, please follow up via email to en
could also be "to notify"

2023-07-12 19:49 UTC, johnrballard commented on SECURITY.md
> +Instead, please open a [security advisory][advisory] which notify the maintainers. You should receive a response within 3 working days. If for some reason you do not, please follow up via email to en
Shoot.  Didn't catch that.

2023-07-18 18:46 UTC, eeeebbbbrrrr approved these changes

2023-07-18 18:47 UTC, merged